export const KOUTALIDIS_PRACTICE_AREAS = [
  {
    id: 'banking',
    name: 'Banking & Finance',
    nameEl: 'Τραπεζικό Δίκαιο',
    icon: 'bank',
    color: '#c5032a',
    sortOrder: 1,
  },
  {
    id: 'ma',
    name: 'M&A',
    nameEl: 'Συγχωνεύσεις & Εξαγορές',
    icon: 'briefcase',
    color: '#7c3aed',
    sortOrder: 2,
  },
  {
    id: 'energy',
    name: 'Energy',
    nameEl: 'Ενέργεια',
    icon: 'bolt',
    color: '#059669',
    sortOrder: 3,
  },
  {
    id: 'litigation',
    name: 'Litigation',
    nameEl: 'Δικαστηριακό',
    icon: 'gavel',
    color: '#d97706',
    sortOrder: 4,
  },
  {
    id: 'digital',
    name: 'Digital / TMT',
    nameEl: 'Ψηφιακό / TMT',
    icon: 'monitor',
    color: '#2563eb',
    sortOrder: 5,
  },
  {
    id: 'tax',
    name: 'Tax',
    nameEl: 'Φορολογικό',
    icon: 'calculator',
    color: '#dc2626',
    sortOrder: 6,
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    nameEl: 'Ακίνητα',
    icon: 'building',
    color: '#0891b2',
    sortOrder: 7,
  },
]

export const BANKING_TOOLS = [
  // Document Generation
  {
    id: 'cp-checklist',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'CP Checklist',
    nameEl: 'CP Checklist',
    description: 'Extract Conditions Precedent from Bond Subscription Agreements into structured checklists',
    icon: 'fileCheck',
    sortOrder: 1,
    toolType: 'document-generation',
  },
  {
    id: 'security-perfection',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Security Perfection',
    nameEl: 'Security Perfection Steps',
    description: 'Generate perfection steps plans from security documents',
    icon: 'file',
    sortOrder: 2,
    toolType: 'document-generation',
  },
  {
    id: 'signing-agenda',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Signing Agenda',
    nameEl: 'Signing Agenda',
    description: 'Prepare complete signing agendas listing all documents for execution',
    icon: 'file',
    sortOrder: 3,
    toolType: 'document-generation',
  },
  {
    id: 'bond-certificates',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Bond Certificates',
    nameEl: 'Bond Certificates',
    description: "Draft bond certificates from templates using the Agent's details",
    icon: 'file',
    sortOrder: 4,
    toolType: 'document-generation',
  },
  {
    id: 'bond-programme',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Bond Programme',
    nameEl: 'Bond Loan Programme',
    description: 'Draft bond loan programmes from precedents and term sheets',
    icon: 'file',
    sortOrder: 5,
    toolType: 'document-generation',
  },
  {
    id: 'engagement-letter',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Engagement Letter',
    nameEl: 'Engagement Letter',
    description: 'Prepare engagement letters from KLF template and fee proposals',
    icon: 'file',
    sortOrder: 6,
    toolType: 'document-generation',
  },
  {
    id: 'court-orders',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Court Orders & Notices',
    nameEl: 'Δικαστικές Αποφάσεις & Ειδοποιήσεις',
    description: 'Generate court orders, bond requests, and notices from templates',
    icon: 'file',
    sortOrder: 7,
    toolType: 'document-generation',
  },
  // Document Review
  {
    id: 'programme-review',
    practiceAreaId: 'banking',
    category: 'Document Review',
    name: 'Programme Review',
    nameEl: 'Programme Review',
    description: 'Review counterparty drafts against internal templates, flag deviations, suggest wording',
    icon: 'fileCheck',
    sortOrder: 1,
    toolType: 'document-review',
  },
  {
    id: 'query-review',
    practiceAreaId: 'banking',
    category: 'Document Review',
    name: 'Query Review',
    nameEl: 'Query Review',
    description: 'Search executed programmes for provisions relevant to specific client queries',
    icon: 'fileCheck',
    sortOrder: 2,
    toolType: 'document-review',
  },
  {
    id: 'dd-review',
    practiceAreaId: 'banking',
    category: 'Document Review',
    name: 'Finance DD Review',
    nameEl: 'Finance DD Review',
    description: 'Review finance documents for risks, change of control, mandatory prepayment, consent requirements',
    icon: 'fileCheck',
    sortOrder: 3,
    toolType: 'document-review',
  },
  // Translation
  {
    id: 'en-gr-translation',
    practiceAreaId: 'banking',
    category: 'Translation',
    name: 'EN↔GR Translation',
    nameEl: 'Μετάφραση EN↔GR',
    description: 'Translate security documents with established legal terminology for official filings',
    icon: 'languages',
    sortOrder: 1,
    toolType: 'translation',
  },
]

export const MA_TOOLS = [
  {
    id: 'dd-report',
    practiceAreaId: 'ma',
    category: 'Due Diligence',
    name: 'DD Report',
    nameEl: 'Έκθεση Due Diligence',
    description: 'Generate structured DD reports with findings categorized by risk level',
    icon: 'file',
    sortOrder: 1,
    toolType: 'document-generation',
  },
  {
    id: 'red-flag-analysis',
    practiceAreaId: 'ma',
    category: 'Due Diligence',
    name: 'Red Flag Analysis',
    nameEl: 'Ανάλυση Red Flag',
    description: 'Identify and analyze red flags from transaction documents',
    icon: 'fileCheck',
    sortOrder: 2,
    toolType: 'document-review',
  },
  {
    id: 'spa-review',
    practiceAreaId: 'ma',
    category: 'Transaction Docs',
    name: 'SPA Review',
    nameEl: 'Έλεγχος SPA',
    description: 'Review SPAs for key provisions, negotiation points, and missing terms',
    icon: 'fileCheck',
    sortOrder: 1,
    toolType: 'document-review',
  },
  {
    id: 'disclosure-letter',
    practiceAreaId: 'ma',
    category: 'Transaction Docs',
    name: 'Disclosure Letter',
    nameEl: 'Disclosure Letter',
    description: 'Draft disclosure letters structured against SPA warranties',
    icon: 'file',
    sortOrder: 2,
    toolType: 'document-generation',
  },
]
