export const KOUTALIDIS_PRACTICE_AREAS = [
  {
    id: 'banking',
    name: 'Banking & Finance',
    nameEl: 'Τραπεζικό Δίκαιο',
    icon: 'bank',
    color: '#c5032a',
    sortOrder: 1,
  },
  {
    id: 'ma',
    name: 'M&A',
    nameEl: 'Συγχωνεύσεις & Εξαγορές',
    icon: 'briefcase',
    color: '#7c3aed',
    sortOrder: 2,
  },
  {
    id: 'energy',
    name: 'Energy',
    nameEl: 'Ενέργεια',
    icon: 'bolt',
    color: '#059669',
    sortOrder: 3,
  },
  {
    id: 'litigation',
    name: 'Litigation',
    nameEl: 'Δικαστηριακό',
    icon: 'gavel',
    color: '#d97706',
    sortOrder: 4,
  },
  {
    id: 'digital',
    name: 'Digital / TMT',
    nameEl: 'Ψηφιακό / TMT',
    icon: 'monitor',
    color: '#2563eb',
    sortOrder: 5,
  },
  {
    id: 'tax',
    name: 'Tax',
    nameEl: 'Φορολογικό',
    icon: 'calculator',
    color: '#dc2626',
    sortOrder: 6,
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    nameEl: 'Ακίνητα',
    icon: 'building',
    color: '#0891b2',
    sortOrder: 7,
  },
]

export const BANKING_TOOLS = [
  // Document Generation
  {
    id: 'cp-checklist',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'CP Checklist',
    nameEl: 'CP Checklist',
    icon: 'fileCheck',
    sortOrder: 1,
    toolType: 'document-generation',
  },
  {
    id: 'security-perfection',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Security Perfection',
    nameEl: 'Security Perfection Steps',
    icon: 'file',
    sortOrder: 2,
    toolType: 'document-generation',
  },
  {
    id: 'signing-agenda',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Signing Agenda',
    nameEl: 'Signing Agenda',
    icon: 'file',
    sortOrder: 3,
    toolType: 'document-generation',
  },
  {
    id: 'bond-certificates',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Bond Certificates',
    nameEl: 'Bond Certificates',
    icon: 'file',
    sortOrder: 4,
    toolType: 'document-generation',
  },
  {
    id: 'bond-programme',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Bond Programme',
    nameEl: 'Bond Loan Programme',
    icon: 'file',
    sortOrder: 5,
    toolType: 'document-generation',
  },
  {
    id: 'engagement-letter',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Engagement Letter',
    nameEl: 'Engagement Letter',
    icon: 'file',
    sortOrder: 6,
    toolType: 'document-generation',
  },
  {
    id: 'court-orders',
    practiceAreaId: 'banking',
    category: 'Document Generation',
    name: 'Court Orders',
    nameEl: 'Court Orders',
    icon: 'file',
    sortOrder: 7,
    toolType: 'document-generation',
  },
  // Document Review
  {
    id: 'programme-review',
    practiceAreaId: 'banking',
    category: 'Document Review',
    name: 'Programme Review',
    nameEl: 'Programme Review',
    icon: 'fileCheck',
    sortOrder: 1,
    toolType: 'document-review',
  },
  {
    id: 'query-review',
    practiceAreaId: 'banking',
    category: 'Document Review',
    name: 'Query Review',
    nameEl: 'Query Review',
    icon: 'fileCheck',
    sortOrder: 2,
    toolType: 'document-review',
  },
  {
    id: 'dd-review',
    practiceAreaId: 'banking',
    category: 'Document Review',
    name: 'DD Review',
    nameEl: 'Finance DD Review',
    icon: 'fileCheck',
    sortOrder: 3,
    toolType: 'document-review',
  },
  // Translation
  {
    id: 'en-gr-translation',
    practiceAreaId: 'banking',
    category: 'Translation',
    name: 'EN↔GR Translation',
    nameEl: 'Μετάφραση EN↔GR',
    icon: 'languages',
    sortOrder: 1,
    toolType: 'translation',
  },
]

export const MA_TOOLS = [
  {
    id: 'dd-report',
    practiceAreaId: 'ma',
    category: 'Due Diligence',
    name: 'DD Report',
    nameEl: 'Έκθεση Due Diligence',
    icon: 'file',
    sortOrder: 1,
    toolType: 'document-generation',
  },
  {
    id: 'red-flag-analysis',
    practiceAreaId: 'ma',
    category: 'Due Diligence',
    name: 'Red Flag Analysis',
    nameEl: 'Ανάλυση Red Flag',
    icon: 'fileCheck',
    sortOrder: 2,
    toolType: 'document-review',
  },
  {
    id: 'spa-review',
    practiceAreaId: 'ma',
    category: 'Transaction Docs',
    name: 'SPA Review',
    nameEl: 'Έλεγχος SPA',
    icon: 'fileCheck',
    sortOrder: 1,
    toolType: 'document-review',
  },
  {
    id: 'disclosure-letter',
    practiceAreaId: 'ma',
    category: 'Transaction Docs',
    name: 'Disclosure Letter',
    nameEl: 'Disclosure Letter',
    icon: 'file',
    sortOrder: 2,
    toolType: 'document-generation',
  },
]
